const nuances = {
  "Extrême gauche": "DarkRed",
  "Parti communiste français": "Red",
  "La France insoumise": "Crimson",
  "Parti socialiste": "LightCoral",
  "Parti radical de gauche": "LightSalmon",
  "Divers gauche": "Brown",
  Ecologiste: "Green",
  Divers: "Grey",
  Régionaliste: "SaddleBrown",
  "La République en marche": "DarkViolet",
  Modem: "DarkOrange",
  "Union des Démocrates et Indépendants": "RoyalBlue",
  "Les Républicains": "MediumBlue",
  "Divers droite": "DodgerBlue",
  "Debout la France": "DarkBlue",
  "Front National": "MidnightBlue",
  "Extrême droite": "Black",
};
